export const ADMIN = {
	ViewAssets: '/view-assets',
	ActionItems: '/Actions-List',
	Dashboard: '/Dashboard',
	Apploader: '/apploader',
	Procedures: '/procedures',
	Documents: '/Documents',
	Certification: '/Certification-Management',
	AddMProcedure: '/procedure/Add',
	AddlIncidentReporting: '/Addl-Incident-Reporting',
	AddlMeetingReport: '/add-meeting-report',
	AddlRisk: '/Risk-Assessment-Matrix',
	HazopAnalysis: '/Hazop-Analysis',
	ViewReports: '/QHSEReports-List',
	MeetingReportsList: '/Meetings-List',
	RiskAssessmentsList: '/Risk-Assessments',
	HanzopAnalysisLst: '/HAZOP-Assessments',
	Certificates: '/Certificates-Management',
	ReportMeeting: '/Reporter-Master-Settings',
};
