
export const ADMIN = {
	Sparepart: '/spareparts',
	ViewAssets:'/view-assets',
	work:'/work-orders',
	workcreate:'/work-orders/create',
	ActionItems :'/Actions-List',
	Dashboard:'/Dashboard',
	Apploader:'/apploader',
	Storemanagement:'/spareparts/store-management',
	Procedures:'/procedures',
	Documents:'/Documents',
	Certification:'/Certification-Management',
	Suppliers:'/suppliers',
	CreateAssets:'/assets/add',
	CreateSpare:'/sparepart/add',
	BulkAdd:'/sparepart/BulkAdd',
	AddMProcedure:'/procedure/Add',
	AddNewDocument:'/Documents/create-document',
	AddLocations:'/add-location',
	AddlIncidentReporting:'/Addl-Incident-Reporting',
	AddlMeetingReport:'/add-meeting-report',
	AddlRisk:'/Risk-Assessment-Matrix',
	HazopAnalysis:'/Hazop-Analysis',
	ViewReports:'/QHSEReports-List',
	MeetingReportsList:'/Meetings-List',
	RiskAssessmentsList:'/Risk-Assessments',
	HanzopAnalysisLst:'/HAZOP-Assessments',
	Certificates:'/Certificates-Management',
	ReportMeeting:'/Reporter-Master-Settings',
};
