export const ADMIN = {
	Sparepart: '/spareparts',
	ViewAssets: '/view-assets',
	work: '/work-orders',
	workcreate: '/work-orders/create',
	Licenses: '/Licenses-Management',
	Dashboard: '/Dashboard',
	Apploader: '/apploader',
	Storemanagement: '/spareparts/store-management',
	Procedures: '/procedures',
	Documents: '/Documents',
	Locations: '/Locations',
	Suppliers: '/suppliers',
	CreateAssets: '/assets/add',
	CreateSpare: '/sparepart/add',
	BulkAdd: '/sparepart/BulkAdd',
	AddMProcedure: '/procedure/Add',
	AddNewDocument: '/Documents/create-document',
	AddLocations: '/add-location',
	AddSupplier: '/add-supplier',
};
