import { BASE_URL } from '../endpoints';

const ACTIONITEMS_BASE_URL = `${BASE_URL}/action-items/`;
const ACTIONITEMSDELEGATE= `${ACTIONITEMS_BASE_URL}report-approval`;
const ACTIONITEMSDELETE= `${ACTIONITEMS_BASE_URL}delete`;
const ACTIONFOLLOWUP= `${ACTIONITEMS_BASE_URL}update-follow-up`;

export const ACTIONITEMS  = {
	ACTIONITEMS_BASE_URL,
	ACTIONITEMSDELEGATE,
	ACTIONFOLLOWUP,
	ACTIONITEMSDELETE
};

