import { BASE_URL } from '../endpoints';

const CERTIFICATE_BASE_URL = `${BASE_URL}/certificate/`;
const CERTIFICATEGET = `${CERTIFICATE_BASE_URL}getallcertification`;
const CERTIFICATEGETASSIGNMENT = `${CERTIFICATE_BASE_URL}user-assignments`;
const CERTIFICATEGETASSIGNMENT2 = `${CERTIFICATE_BASE_URL}assignmentsbycertId`;

export {
	CERTIFICATE_BASE_URL,
	CERTIFICATEGET,
	CERTIFICATEGETASSIGNMENT,
	CERTIFICATEGETASSIGNMENT2
};
